# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
