# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0004_diet_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diet',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
