# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0007_auto_20180202_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='urlshort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='diet',
            name='payment',
        ),
        migrations.AddField(
            model_name='diet',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diet',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urlshort',
            name='dietplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.diet'),
        ),
    ]
